# Generated by Django 4.2.4 on 2023-08-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_customer_customer_number_meterreading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
