# Generated by Django 4.2.4 on 2023-08-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_customer_user_remove_customer_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
